name: advanced_model_serialization
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  reflectable: ^4.0.10
  ansicolor: ^2.0.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
